[package]
name = "servo-vdom-client"
version = "0.1.0"
authors = ["Loren Van Spronsen <lorenvs@outlook.com>"]

[dependencies]
byteorder="*"
serde="*"
serde_json="*"

[dependencies.ipc-channel]
git = "https://github.com/servo/ipc-channel"